export const movies = [
  {
    id: 1,
    name: 'Dangal',
    genre: 'Biographical Sports Drama',
    country: 'India',
    releaseYear: 2016,
    rating: 8.4,
    duration: '161 min',
    director: 'Nitesh Tiwari',
    cast: ['Aamir Khan', 'Fatima Sana Shaikh', 'Sanya Malhotra'],
    description: 'Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.',
    bannerUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQMCj20Dhxm40PDsgiS1lMZaNj8lepMfMv9zn3LsbwLWu2ovzUk',
    trailerUrl: 'https://www.youtube.com/watch?v=x_7YlGv9u1g'
  },
  {
    id: 2,
    name: 'Baahubali 2: The Conclusion',
    genre: 'Epic Action',
    country: 'India',
    releaseYear: 2017,
    rating: 8.2,
    duration: '167 min',
    director: 'S.S. Rajamouli',
    cast: ['Prabhas', 'Rana Daggubati', 'Anushka Shetty'],
    description: 'When Shiva, the son of Bahubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events that unfolded in the Mahishmati Kingdom.',
    bannerUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTnMA16Y55ki6WxoLTdTmxNnKwYCZiNwi0DvCakttCRBQgZyJpJ',
    trailerUrl: 'https://www.youtube.com/watch?v=G62HrubdD6o'
  },
  {
    id: 3,
    name: 'RRR',
    genre: 'Action Drama',
    country: 'India',
    releaseYear: 2022,
    rating: 7.9,
    duration: '187 min',
    director: 'S.S. Rajamouli',
    cast: ['N.T. Rama Rao Jr.', 'Ram Charan', 'Alia Bhatt'],
    description: 'A fictitious story about two legendary revolutionaries and their journey away from home before they started fighting for their country in 1920s.',
    bannerUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRx0wTDoneV8OuMM6hNfD7vfibB_jt6FcCL-u8H2DljlRXgGCoG',
    trailerUrl: 'https://www.youtube.com/watch?v=f_vbAtFSEc0'
  },
  {
    id: 4,
    name: 'K.G.F: Chapter 2',
    genre: 'Action Thriller',
    country: 'India',
    releaseYear: 2022,
    rating: 8.3,
    duration: '168 min',
    director: 'Prashanth Neel',
    cast: ['Yash', 'Sanjay Dutt', 'Raveena Tandon'],
    description: 'The blood-soaked land of Kolar Gold Fields (KGF) has a new overlord now - Rocky, whose name strikes fear in the heart of his foes.',
    bannerUrl: 'https://m.media-amazon.com/images/M/MV5BZmQzZjVkZTUtYjI4ZC00ZDJmLWI0ZDUtZTFmMGM1Mzc5ZjIyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=JKa05nyUmuQ'
  },
  {
    id: 5,
    name: 'Jawan',
    genre: 'Action Thriller',
    country: 'India',
    releaseYear: 2023,
    rating: 7.1,
    duration: '169 min',
    director: 'Atlee',
    cast: ['Shah Rukh Khan', 'Nayanthara', 'Vijay Sethupathi'],
    description: 'A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society.',
    bannerUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8fxJgOk6Q4UGjmsa1q3CQ1Q05Lt0Dn1leAl6_KexCEjqJAe6',
    trailerUrl: 'https://www.youtube.com/watch?v=MWOlnZSnXJo'
  },
  {
    id: 6,
    name: 'Pathaan',
    genre: 'Action Thriller',
    country: 'India',
    releaseYear: 2023,
    rating: 6.1,
    duration: '146 min',
    director: 'Siddharth Anand',
    cast: ['Shah Rukh Khan', 'Deepika Padukone', 'John Abraham'],
    description: 'An exiled RAW agent partners with a Pakistani agent to take down a shared enemy.',
    bannerUrl: 'https://m.media-amazon.com/images/M/MV5BNDdkNTY1MDQtY2I5MC00OTFlLTg5OWQtZWE2YzE5NWFiMDgzXkEyXkFqcGc@._V1_.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=vqu4z34wENw'
  },
  {
    id: 7,
    name: '3 Idiots',
    genre: 'Comedy Drama',
    country: 'India',
    releaseYear: 2009,
    rating: 8.4,
    duration: '170 min',
    director: 'Rajkumar Hirani',
    cast: ['Aamir Khan', 'R. Madhavan', 'Sharman Joshi'],
    description: 'Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them.',
    bannerUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/df/3_idiots_poster.jpg/250px-3_idiots_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=K0eDlFX9GMc'
  },
  {
    id: 8,
    name: 'Avatar: The Way of Water',
    genre: 'Science Fiction',
    country: 'USA',
    releaseYear: 2022,
    rating: 7.6,
    duration: '192 min',
    director: 'James Cameron',
    cast: ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver'],
    description: 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora.',
    bannerUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSYWVMx6h59vKIGkku5l3hPkBbqsErDsCB7-QZ9zaKuhTN8edvL',
    trailerUrl: 'https://www.youtube.com/watch?v=d9MyW72ELq0'
  },
  {
    id: 9,
    name: 'Avengers: Endgame',
    genre: 'Superhero Action',
    country: 'USA',
    releaseYear: 2019,
    rating: 8.4,
    duration: '181 min',
    director: 'Anthony Russo, Joe Russo',
    cast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo'],
    description: 'After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos actions and restore balance.',
    bannerUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRXef9DJnZiq5az0UnjkmvkQufOQ5MFnF7HATYRUXN913swRuH1',
    trailerUrl: 'https://www.youtube.com/watch?v=TcMBFSGVi1c'
  },
  {
    id: 10,
    name: 'The Dark Knight',
    genre: 'Superhero Action',
    country: 'USA',
    releaseYear: 2008,
    rating: 9.0,
    duration: '152 min',
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests.',
    bannerUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQkUywIUXDjHSQJIaNHYVs08osgBpF5Ot-xmB_omyEZeeRP9Xug',
    trailerUrl: 'https://www.youtube.com/watch?v=EXeTwQWrcwY'
  }
];
